Some older GCC versions produce following error when x86 MSR modules are build:
  In file included from commands/i386/rdmsr.c:29:0:
  ../include/grub/i386/rdmsr.h:27:29: error: no previous prototype for ‘grub_msr_read’ [-Werror=missing-prototypes]
   extern inline grub_uint64_t grub_msr_read (grub_uint32_t msr_id)
                               ^
  cc1: all warnings being treated as errors

This is due to incorrect use of extern keyword. So, replace it with
static keyword.

Additionally, fix incorrect coding style.